config/routes.rb
Rails.application.routes.draw do
  namespace :page do
    get 'calc/index'
  end
  namespace :users_office do
    resources :fees
  end
  namespace :users_office do
    resources :calls
  end
  namespace :users_office do
    resources :safeties
  end
  namespace :users_office do
    resources :privacies
  end
  namespace :users_office do
    resources :terms
  end
  namespace :users_office do
    resources :complaints
  end
  namespace :users_office do
    resources :contacts
  end
  namespace :page do
    get 'tariff/index'
  end
  namespace :page do
    get 'contact/index'
    post 'contact/new'
    get 'complaint/index'
    post 'complaint/new'
    get 'fee/index'
    post 'fee/new'
  end
  namespace :page do
    get 'risk/index'
  end
  namespace :page do
    get 'socio/index'
  end
  namespace :page do
    get 'education/index'
  end
  namespace :page do
    get 'demo/index'
  end
  namespace :page do
    get 'credit/index'
  end
  namespace :page do
    get 'correspodent/index'
  end
  namespace :page do
    get  'who/index'
    get  'calc/index'
    post 'calc/enviar'
    post 'calc/reenviar'
  end
  mount Ckeditor::Engine => '/ckeditor'
  namespace :page do
    get 'welcome/index'
    get 'info/index'
  end
  namespace :users_office do
    resources :tariffs
  end
  namespace :users_office do
    resources :credits
  end
  namespace :users_office do
    resources :risks
  end
  namespace :users_office do
    resources :repossibilities
  end
  namespace :users_office do
    resources :educations
  end
  namespace :users_office do
    resources :demos
  end
  namespace :users_office do
    resources :correspondets
  end
  namespace :users_office do
    resources :whos
  end
  namespace :users_office do
    resources :products
  end
  namespace :users_office do
    resources :footers
  end
  namespace :users_office do
    resources :images
  end
  namespace :users_office do
    get 'users/index'
    resources :users
  end
  
  devise_for :users

  namespace :users_office do
    get 'welcome/index'
  end
  namespace :site do
    get 'welcome/index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'site/welcome#index'
  
  get '/inicio', to: 'site/welcome#index'
  get '/informacoes', to: 'page/info#index'
  get '/produtos', to: 'page/welcome#index'
  get '/quem-somos', to: 'page/who#index'
  get '/correspodentes', to: 'page/correspodent#index'
  get '/demonstracoes-financeiras', to: 'page/demo#index'
  get '/educacao-financeira', to: 'page/education#index'
  get '/politica-responsabilidade-socio-ambiental-prs', to: 'page/socio#index'
  get '/tabela-de-risco', to: 'page/risk#index'
  get '/tabela-de-tarifas', to: 'page/tariff#index'
  get '/sistema-de-informacao-de-credito-scr', to: 'page/credit#index'
  get '/contato', to: 'page/contact#new'
  get '/denuncia', to: 'page/complaint#new'
  get '/painel-administrativo/sign-in', to: 'users_office/welcome#index'
  get '/termos-de-uso', to: 'page/terms#index'
  get '/politica-de-privacidade', to: 'page/privacy#index'
  get '/seguranca', to: 'page/safety#index'
  get '/relatorio-ouvidoria', to: 'page/call#index'
  get '/denuncia-anonima', to: 'page/fee#new'
  get '/simulador-de-consignado', to: 'page/calc#index'
  #post '/simulador-de-consignado', to: 'page/calc/index'
  post '/simulador-de-consignado', to: 'page/calc#enviar'
  post '/simulador-de-consignado', to: 'page/calc#reenviar'


  #rotas admins

  get '/admin/home', to: 'users_office/welcome#index'
  get '/admin/imagens', to: 'users_office/images#index'
  get '/admin/correspodentes', to: 'users_office/correspondets#index'
  get '/admin/demonstracao-financeira', to: 'users_office/demos#index'
  get '/admin/educacao-financeira', to: 'users_office/educations#index'

  get '/admin/politica-de-privacidade', to: 'users_office/privacies#index'
  get '/admin/politica-responsabilidade-socioambiental', to: 'users_office/repossibilities#index'
  get '/admin/tabela-de-risco', to: 'users_office/risks#index'
  get '/admin/seguranca', to: 'users_office/safeties#index'
  get '/admin/sistema-de-informacoes-de-credito', to: 'users_office/credits#index'

  get '/admin/tabela-de-tarifas', to: 'users_office/tariffs#index'
  get '/admin/termos-de-uso', to: 'users_office/terms#index'
  get '/admin/contatos', to: 'users_office/contacts#index'
  get '/admin/denuncias', to: 'users_office/complaints#index'

  get '/admin/produtos', to: 'users_office/products#index'
  get '/admin/quem-somos', to: 'users_office/whos#index'
  get '/admin/rodape', to: 'users_office/footers#index'
  get '/admin/usuarios', to: 'users_office/users#index'
  get '/admin/ouvidoria', to: 'users_office/calls#index'
  get '/admin/denuncia-anonima', to: 'users_office/fees#index'
 end

app/models/users_office.rb
module UsersOffice
  def self.table_name_prefix
    'users_office_'
  end
end

app/models/users_office/call.rb
class UsersOffice::Call < ApplicationRecord
  has_rich_text :content
end

app/models/users_office/complaint.rb
class UsersOffice::Complaint < ApplicationRecord
end

app/models/users_office/contact.rb
class UsersOffice::Contact < ApplicationRecord
  has_rich_text :content
end

app/models/users_office/correspondet.rb
class UsersOffice::Correspondet < ApplicationRecord
  has_rich_text :content
end

app/models/users_office/credit.rb
class UsersOffice::Credit < ApplicationRecord
  has_rich_text :content
end

app/models/users_office/demo.rb
class UsersOffice::Demo < ApplicationRecord
  has_rich_text :content
end

app/models/users_office/education.rb
class UsersOffice::Education < ApplicationRecord
  has_rich_text :content
end

app/models/users_office/fee.rb
class UsersOffice::Fee < ApplicationRecord
end

app/models/users_office/footer.rb
class UsersOffice::Footer < ApplicationRecord
  has_rich_text :content
end

app/models/users_office/image.rb
class UsersOffice::Image < ApplicationRecord
  has_one_attached :avatar
  has_rich_text :content
end

app/models/users_office/privacy.rb
class UsersOffice::Privacy < ApplicationRecord
  has_rich_text :content
end

app/models/users_office/product.rb
class UsersOffice::Product < ApplicationRecord
  has_rich_text :subtitle
end

app/models/users_office/repossibility.rb
class UsersOffice::Repossibility < ApplicationRecord
  has_rich_text :content
end

app/models/users_office/risk.rb
class UsersOffice::Risk < ApplicationRecord
  has_rich_text :content
end

app/models/users_office/safety.rb
class UsersOffice::Safety < ApplicationRecord
  has_rich_text :content
end

app/models/users_office/tariff.rb
class UsersOffice::Tariff < ApplicationRecord
  has_rich_text :content
end

app/models/users_office/term.rb
class UsersOffice::Term < ApplicationRecord
  has_rich_text :content
end

app/models/users_office/who.rb
class UsersOffice::Who < ApplicationRecord
  has_rich_text :subtitle
end

app/controllers/page/credit_controller.rb
class Page::CreditController < PageController
  def index
    @users_office_footers = UsersOffice::Footer.all
    @users_office_credits = UsersOffice::Credit.all
  end
end

app/views/users_office/credits/_form.html.erb
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

<!doctype html>
<!-- https://bootsnipp.com/snippets/GaZG0 -->
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
  


    <link rel="icon" href="Favicon.png">


    <title>Painel Administrativo</title>
</head>

<body> 

<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><strong> <h3> <%= message %></h3> </strong> </div>
                    <div class="card-body">
                            <div class="form-group row">
                                <div class="col-md-12"> 
                                <%= form_with(model: users_office_credit, local: true) do |form| %>
                                      <% if users_office_credit.errors.any? %>
                                        <div id="error_explanation">
                                          <h2><%= pluralize(users_office_credit.errors.count, "error") %> prohibited this users_office_credit from being saved:</h2>

                                          <ul>
                                            <% users_office_credit.errors.full_messages.each do |message| %>
                                              <li><%= message %></li>
                                            <% end %>
                                          </ul>
                                        </div>
                                      <% end %>

                                        <div class="form-group">
                                         <%= form.label :title %>
                                         <%= form.text_field :title, class:"form-control",placeholder:"Insira um Titulo a Imagem" %>
                                         </div>
                                    
                                        <div class="form-group">
                                          <%= form.label :content %>
                                          <%= form.rich_text_area :content, class:"form-control",placeholder:"Conteudo",id: form.object.object_id %>
                                        </div>
                                     
                                         <%= form.submit "Salvar" , class: 'btn btn-primary'%>
                                         <% end %>
                                    
                                </div>
                            </div>
      
                    </div>
                   
                </div>
            </div>
        </div>
    </div>
    </div>

</main>
</body>
</html>

app/views/users_office/credits/edit.html.erb
<%= render 'form', users_office_credit: @users_office_credit, message: 'Editando Sistema de Informações de Crédito - SCR ' %>

app/views/users_office/credits/index.html.erb
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
     

    <link rel="icon" href="Favicon.png">


    <title>Painel Administrativo</title>
</head>
<body>

<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><strong> <h3> Listando Sistema de Informações de Crédito - SCR </h3> </strong>  </div>
                    <div class="card-body">
                          <div class="alert alert-success alert-dismissible fade show" role="alert" id="notice">
                              <strong> <%= notice %> </strong>
                              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-12">
                                    <div class="table-responsive">
                                       <table class="table table-striped table-bordered table-hover">
                                        <thead>
                                          <tr>
                                          <th>#</th>
                                          <th>Titulo</th>
                                          <th>Conteudo</th>
                                          <th>Editar</th>
                                          <th>Excluir</th>
                                           <td style="width: 100px">
                                          <%= link_to new_users_office_credit_path , class:"btn btn-success btn-circle" do %>
                                          <i class="fa fa-plus"></i>
                                          <% end %>
                                          </td>
                                         </tr>
                                       </thead>
                                         <tbody>
                                         <% @users_office_credits.each do |users_office_credit| %>
                                          <tr>
                                          <td><%= users_office_credit.id%></td>
                                           <td><%= users_office_credit.title %></td>
                                            <td><%= users_office_credit.content %></td>
                                          <td style="width: 100px">
                                          <%= link_to edit_users_office_credit_path(users_office_credit), class:"btn btn-primary btn-circle" do %>
                                             <i class="fa fa-edit"></i>
                                            <% end %>
                                          </td>
                                          <td style="width: 100px">
                                          <%= link_to users_office_credit, method: :delete, data: { confirm: 'Tem Certeza?' } , class: "btn btn-danger btn-circle" do %>
                                          <%#= link_to 'Destroy', users_office_image, method: :delete, data: { confirm: 'Are you sure?' } %>
                                          <i class="fa fa-minus"></i>
                                          <% end %>
                                          </td>
                                          
                                          </tr>
                                          <% end %>
                                          </tbody>
                                          </table>
                                            
                                             <%#= paginate @users, class: 'text-center' %>
                                           
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

   
</main>

app/views/users_office/credits/new.html.erb
<%= render 'form', users_office_credit: @users_office_credit, message: 'Novo Sistema de Informações de Crédito - SCR ' %>

app/views/users_office/credits/show.html.erb
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
     

    <link rel="icon" href="Favicon.png">


    <title>Painel Administrativo</title>
</head>
<body>

<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><strong> <h3> Mostrando Sistema de Informações de Crédito - SCR </h3> </strong>  </div>
                    <div class="card-body">
                        <div class="alert alert-success alert-dismissible fade show" role="alert" id="notice">
                              <strong> <%= notice %> </strong>
                              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>  
                            <div class="form-group row">
                                <div class="col-md-12">
                                    <div class="table-responsive">
                                       <table class="table table-striped table-bordered table-hover">
                                        <thead>
                                          <tr>
                                           <th>#</th>
                                           <th>Titulo</th>
                                           <th>Conteudo</th>
                                           <th>Editar</th>
                                           <th>Voltar </th>
                                           <td style="width: 100px">
                                          <%= link_to new_users_office_credit_path, class:"btn btn-success btn-circle" do %>
                                          <i class="fa fa-plus"></i>
                                          <% end %>
                                          </td>
                                         </tr>
                                       </thead>
                                         <tbody>
                                         <%# @users.each do |user| %>
                                          <tr>
                                          <td><%= @users_office_credit.id%></td>
                                          <td><%= @users_office_credit.title%></td>
                                          <td><%= @users_office_credit.content%></td>
                                          <td style="width: 100px">
                                          <%= link_to edit_users_office_credit_path(@users_office_credit), class:"btn btn-primary btn-circle" do %>
                                             <i class="fa fa-mail-reply"></i>
                                            <% end %>
                                          </td>
                                          <td style="width: 100px">
          
                                          <%= link_to users_office_credits_path, class: "btn btn-warning btn-circle" do %>
                                          <i class="fa fa-minus"></i>
                                          <% end %>
                                          </td>
                                          
                                          </tr>
                                          <%# end %>
                                          </tbody>
                                          </table>
                                            
                                             <%#= paginate @users, class: 'text-center' %>
                                           
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

   
</main>